add_lunch_combo bolt_angler-userdebug
add_lunch_combo bolt_bullhead-userdebug
add_lunch_combo bolt_flo-userdebug
add_lunch_combo bolt_hammerhead-userdebug
add_lunch_combo bolt_mako-userdebug
add_lunch_combo bolt_shamu-userdebug
